'use client'

// import type { Metadata } from "next";
import localFont from "next/font/local";
import { usePathname } from 'next/navigation';
import "./globals.css";
import Navbar from "./navbar/page";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const hideHeaderOnRoutes = ['/login', '/signup'];

  const shouldHideHeader = hideHeaderOnRoutes.includes(pathname);
  return (
    <html lang="en">
      <body className="">
        {!shouldHideHeader && <Navbar />}
        {children}
      </body>
    </html>
  );
}
